export const copy = {
  appName: 'DSH Bridge',
  scanning: '扫描局域网端口中...',
  checkingHistory: '寻找可用连接',
  cancel: '取消',
  autoScan: '自动扫描局域网',
  scanQr: '扫码连接',
  recentConnections: '最近连接',
  refreshConnections: '刷新最近连接',
  connectionInfo: '连接信息',
  currentConnection: '当前连接',
  noConnection: '尚未连接',
  noHistory: '暂无最近连接',
  noHistoryAvailable: '未找到可用的历史连接，请选择连接方式。',
  reconnect: '重新连接',
  disconnect: '断开连接',
  swipeHint: '向左滑查看连接信息',
  swipeAccessibility: '关闭滑动引导',
  closeDrawer: '关闭连接信息',
  closeScanner: '关闭扫码',
  cameraTitle: '扫码连接 DSH Bridge',
  cameraHint: '扫描桌面端或 DSH Bridge 中的连接二维码',
  cameraPermission: '需要相机权限才能扫描连接二维码。',
  allowCamera: '允许使用相机',
  openSettings: '打开系统设置',
  cameraError: '无法打开相机，请检查相机权限后重试。',
  invalidQr: '二维码中没有有效的 HTTP/HTTPS 连接地址。',
  qrRetry: '重新扫码',
  noNetwork: '无法获取局域网 IPv4 地址，请连接 Wi-Fi 或使用扫码连接。',
  noHosts: '未发现可用主机，请检查设备是否在同一局域网，或扫码连接。',
  scanFailed: '扫描失败，请检查网络后重试。',
  connectionFailed: '连接失败，请检查主机地址、网络或访问令牌。',
  focusFailed: '已恢复连接，但未能定位通知对应会话，请在网页中手动选择。',
  hostOffline: '主机暂时不可用',
  tokenRequired: '该主机需要访问令牌，请用桌面端二维码扫码连接，或在页面内登录。',
  loading: '寻找可用连接',
  notificationChannel: '连接与任务通知',
  available: '可用',
  unavailable: '不可用',
  checking: '正在检测',
  storageFailed: '无法读取或保存连接记录，请检查设备存储权限和空间。',
} as const
